rgbd_capture_node:
  ros__parameters:
    rgb_topic: /robot/arm_rgbd_camera/color/image_raw
    depth_topic: /robot/arm_rgbd_camera/depth/image_raw
    camera_info_topic: /robot/arm_rgbd_camera/color/camera_info
    session_dir: /tmp/renee_scan_session
    world_frame: robot_map
    robot_frame: robot_base_link
    camera_frame: robot_arm_rgbd_camera_color_optical_frame # for zed2i use robot_arm_rgbd_camera_left_camera_optical_frame
    sync_tolerance_ms: 1000.0
    tf_timeout_sec: 0.5
